# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast

      #-   repo: https://github.com/Lucas-C/pre-commit-hooks
      #rev: v1.1.9
      #hooks:
      #-   id: forbid-crlf
      #-   id: remove-crlf
      #-   id: forbid-tabs
      #-   id: remove-tabs

-   repo: https://github.com/hadialqattan/pycln
    rev: 0.0.1-beta.3
    hooks:
    - id: pycln
      args: [--config=pyproject.toml]

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -    id: black

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: [--max-line-length, "88", --max-complexity, "10", --extend-ignore, "E203, W503"]

-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint

-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        args: [--in-place]

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
